apiVersion: apps/v1
kind: Deployment
metadata:
  name: failed-message-store-poller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failed-message-store-poller-pod
  template:
    metadata:
      labels:
        app: failed-message-store-poller-pod
    spec:
      containers:
        - image: gcr.io/pnr-order-poc/failed-message-store-poller:latest
          name: failed-message-store-poller
            