apiVersion: apps/v1
kind: Deployment
metadata:
  name: outbox-poller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outbox-poller-pod
  template:
    metadata:
      labels:
        app: outbox-poller-pod
    spec:
      containers:
        - image: gcr.io/pnr-order-poc/outbox-poller:latest
          name: outbox-poller
            